branches:
  only:
    - casperjs
before_script:
 - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
 - drush runserver --server=builtin 8080 &
 - sleep 3 # give Web server some time to bind to sockets, etc
 - cd ..
 - git clone git://github.com/n1k0/casperjs.git
 - cd casperjs
 - git checkout tags/1.0.0
 - cd ./bin

script:
 - "DISPLAY=:99.0 ./casperjs ../tests/test.js"