branches:
  only:
    - casperjs
before_script:
 - cd ..
 - git clone git://github.com/n1k0/casperjs.git
 - cd casperjs
 - git checkout tags/1.0.0
 - cd ./bin

script:
 - "./casperjs ../../todomvc/tests/test.js ../../todomvc/architecture-examples/angularjs/index.html"
 - "./casperjs ../../todomvc/tests/test.js ../../todomvc/architecture-examples/jquery/index.html"
 - "./casperjs ../../todomvc/tests/test.js ../../todomvc/architecture-examples/spine/index.html"
 - "./casperjs ../../todomvc/tests/test.js ../../todomvc/architecture-examples/dart/web/index.html"